### ISSUE TITLE
Following example leaves error

### ISSUE THREAD

**Issue by christoffersch** [bruvzg/godot_sqlite#1]
I went through the same steps as in the example from `README.md`, but received a "Type mismatch, SQLiteStatement expected!" error. 

Data can be read just fine, but it complains about inserting into the `.db` file.

![image](https://user-images.githubusercontent.com/9469461/45110075-94120680-b141-11e8-9ca5-feef15c8c51d.png)

```
Error:
0:00:00:0731 - Type mismatch, SQLiteStatement expected!
----------
Type:Error
Description: 
Time: 0:00:00:0731
C Error: Type mismatch, SQLiteStatement expected!
C Source: ../../../src/godot_sqlite3.c:697
C Function: gdn_sqlite3_prepare
```

It complains about line 20:
`db.prepare("INSERT INTO users (username) VALUES ('PETER')", stmt);`

**Comment by bruvzg** [comment]
I was not able reproduce this issue with freshly built libraries, but get same errors with old (0.1.0 release) Window library and Godot v3.1 alpha 1.
Probably this error happens due to some changes in GDNative headers.

Libraries in release section are replaced with freshly built (v3.1 alpha 1 headers).

**Comment by christoffersch** [comment]
Great, everything should be fine then. Thanks!
